# Generated by Django 4.0.4 on 2022-04-14 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letraSize', models.PositiveIntegerField()),
                ('letraStyle', models.CharField(max_length=30)),
                ('colorFondo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('formato', models.CharField(max_length=5)),
                ('linkDocumento', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='univibesApp.documento')),
                ('ISBN', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=5000)),
                ('autor', models.CharField(max_length=100)),
            ],
            bases=('univibesApp.documento',),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nomUsuario', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50, unique=True)),
                ('esAdmin', models.BooleanField()),
                ('docsAnyadidos', models.ManyToManyField(related_name='+', to='univibesApp.documento')),
                ('docsSubidos', models.ManyToManyField(related_name='+', to='univibesApp.documento')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pagina', models.PositiveIntegerField()),
                ('offset', models.PositiveIntegerField()),
                ('esUltimaLeida', models.BooleanField()),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univibesApp.documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univibesApp.usuario')),
            ],
        ),
    ]
