# Generated by Django 4.0.3 on 2022-03-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('ISBM', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pathLibro', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=50)),
            ],
        ),
    ]
