# Generated by Django 4.0.3 on 2022-05-08 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('formato', models.CharField(max_length=5)),
                ('linkDocumento', models.CharField(max_length=500)),
                ('cover', models.FileField(blank=True, null=True, upload_to='.')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkPortada', models.CharField(max_length=32, null=True)),
                ('autor', models.CharField(max_length=100, null=True)),
                ('editorial', models.CharField(blank=True, max_length=100, null=True)),
                ('valoracion', models.FloatField(default=0.0)),
                ('numValoraciones', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nomUsuario', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('correo', models.CharField(max_length=50, unique=True)),
                ('esAdmin', models.BooleanField()),
                ('letraSize', models.PositiveIntegerField(blank=True, null=True)),
                ('letraStyle', models.CharField(blank=True, max_length=30, null=True)),
                ('colorFondo', models.CharField(blank=True, max_length=30, null=True)),
                ('docsAnyadidos', models.ManyToManyField(related_name='+', to='itreaderApp.libro')),
                ('docsSubidos', models.ManyToManyField(related_name='+', to='itreaderApp.documento')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pagina', models.PositiveIntegerField()),
                ('offset', models.PositiveIntegerField()),
                ('esUltimaLeida', models.BooleanField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itreaderApp.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itreaderApp.usuario')),
            ],
        ),
    ]
