# Generated by Django 4.0.3 on 2022-05-10 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itreaderApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='cover',
        ),
    ]
