# Generated by Django 4.0.3 on 2022-05-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreaderApp', '0002_remove_documento_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='.'),
        ),
    ]
