# Generated by Django 4.0.3 on 2022-05-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreaderApp', '0003_documento_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
