# Generated by Django 4.0.3 on 2022-05-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreaderApp', '0004_alter_documento_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='coverLib',
            field=models.FileField(blank=True, null=True, upload_to='.'),
        ),
    ]
