# Generated by Django 4.0.3 on 2022-03-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nomUsuario', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50, unique=True)),
                ('edad', models.PositiveIntegerField()),
                ('telefono', models.PositiveIntegerField()),
            ],
        ),
    ]
